import Head from 'next/head'
import { Button, Flex, Stack } from '@chakra-ui/react'
import { Input } from '../components/form/Input'

export default function SignIn() {
  return (
    <>
      <Head>
        <title>SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100vw" h="100vh" align="center" justify="center">
        <Flex
          as="form"
          w="100%"
          maxW={360}
          bg="gray.800"
          p="8"
          borderRadius={8}
          flexDir="column"
        >
          <Stack spacing="4">
            <Input 
            name='email'
            label='Email:'
            type='email'
            />
            <Input 
            name='password'
            label='Senha:'
            type='password'
            />
            
          </Stack>


          <Button type='submit' mt="6" colorScheme="pink" size="lg">Entrar</Button>
        </Flex>
      </Flex>
    </>
  )
}
